//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradores
    {
        public int id_administrador { get; set; }
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellidop { get; set; }
        public string apellidom { get; set; }
        public int id_sucursal { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        public virtual Sesiones Sesiones { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
