//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendar_Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agendar_Citas()
        {
            this.Agendar_Citas1 = new HashSet<Agendar_Citas>();
        }
    
        public int id_cita { get; set; }
        public int id_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public int id_trabajador { get; set; }
        public Nullable<int> id_cotizacion { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public System.TimeSpan hora_cita { get; set; }
        public string estado { get; set; }
        public string motivo_cancelacion { get; set; }
        public Nullable<int> cita_anterior { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendar_Citas> Agendar_Citas1 { get; set; }
        public virtual Agendar_Citas Agendar_Citas2 { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Cotizaciones Cotizaciones { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual Registro_Vehiculos Registro_Vehiculos { get; set; }
    }
}
