//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo_Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogo_Vehiculos()
        {
            this.Registro_Vehiculos = new HashSet<Registro_Vehiculos>();
        }
    
        public int id_catalogo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> anio_inicio { get; set; }
        public Nullable<int> anio_fin { get; set; }
        public string tipo_vehiculo { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Vehiculos> Registro_Vehiculos { get; set; }
    }
}
