//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizaciones()
        {
            this.Agendar_Citas = new HashSet<Agendar_Citas>();
            this.Ordenes_Trabajos1 = new HashSet<Ordenes_Trabajos>();
        }
    
        public int id_cotizacion { get; set; }
        public int id_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public decimal total_estimado { get; set; }
        public string estatus { get; set; }
        public Nullable<int> id_orden { get; set; }
        public int vigencia_dias { get; set; }
        public int aprobada_por { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendar_Citas> Agendar_Citas { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual Ordenes_Trabajos Ordenes_Trabajos { get; set; }
        public virtual Registro_Vehiculos Registro_Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Trabajos> Ordenes_Trabajos1 { get; set; }
    }
}
