//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores
    {
        public int LogID { get; set; }
        public Nullable<int> NumeroError { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> Severidad { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Linea { get; set; }
        public string Procedimiento { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    }
}
