//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.Detalles_Inventario = new HashSet<Detalles_Inventario>();
        }
    
        public int id_inventario { get; set; }
        public int id_proveedor { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int cantidad_stock { get; set; }
        public decimal precio_costo { get; set; }
        public decimal precio_venta { get; set; }
        public Nullable<int> unidad_medida { get; set; }
        public int stock_minimo { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Inventario> Detalles_Inventario { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Unidades_de_Medida Unidades_de_Medida { get; set; }
    }
}
