//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public municipios()
        {
            this.sucursales = new HashSet<sucursales>();
        }
    
        public int id_municipio { get; set; }
        public string nombre { get; set; }
        public int id_estado { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        public virtual estados estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursales> sucursales { get; set; }
    }
}
