//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes_Trabajos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes_Trabajos()
        {
            this.Cotizaciones = new HashSet<Cotizaciones>();
            this.Detalles_Inventario = new HashSet<Detalles_Inventario>();
            this.Detalles_Servicios = new HashSet<Detalles_Servicios>();
            this.Servicios_Domicilio = new HashSet<Servicios_Domicilio>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int id_orden { get; set; }
        public int id_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public int id_empleado { get; set; }
        public Nullable<int> id_cotizacion { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string diagnostico { get; set; }
        public string estado_trabajo { get; set; }
        public string observaciones { get; set; }
        public decimal total { get; set; }
        public Nullable<int> kilometraje_ingreso { get; set; }
        public Nullable<int> kilometraje_salida { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
        public virtual Cotizaciones Cotizaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Inventario> Detalles_Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Servicios> Detalles_Servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios_Domicilio> Servicios_Domicilio { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual Registro_Vehiculos Registro_Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
