//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int id_pago { get; set; }
        public int id_orden { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string metodo_pago { get; set; }
        public decimal monto { get; set; }
        public string referencia { get; set; }
        public string estatus { get; set; }
        public string tipo_pago { get; set; }
        public decimal saldo_pendiente { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        public virtual Ordenes_Trabajos Ordenes_Trabajos { get; set; }
    }
}
