//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registro_Vehiculos()
        {
            this.Agendar_Citas = new HashSet<Agendar_Citas>();
            this.Cotizaciones = new HashSet<Cotizaciones>();
            this.Ordenes_Trabajos = new HashSet<Ordenes_Trabajos>();
        }
    
        public int id_vehiculo { get; set; }
        public int id_cliente { get; set; }
        public Nullable<int> id_catalogo { get; set; }
        public string marca { get; set; }
        public string num_serie { get; set; }
        public string color { get; set; }
        public int kilometraje { get; set; }
        public Nullable<System.DateTime> anio { get; set; }
        public string tipo_combustible { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendar_Citas> Agendar_Citas { get; set; }
        public virtual Catalogo_Vehiculos Catalogo_Vehiculos { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Trabajos> Ordenes_Trabajos { get; set; }
    }
}
