//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios_Domicilio
    {
        public int id_servicio_domicilio { get; set; }
        public int id_cliente { get; set; }
        public int id_trabajador { get; set; }
        public int id_orden { get; set; }
        public string direccion_servicio { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> hora_estimada { get; set; }
        public string estado { get; set; }
        public decimal costo_traslado { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Ordenes_Trabajos Ordenes_Trabajos { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
