//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class tallermecanicoEntities1 : DbContext
    {
        public tallermecanicoEntities1()
            : base("name=tallermecanicoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Agendar_Citas> Agendar_Citas { get; set; }
        public virtual DbSet<Auditorias> Auditorias { get; set; }
        public virtual DbSet<Catalogo_Vehiculos> Catalogo_Vehiculos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Cotizaciones> Cotizaciones { get; set; }
        public virtual DbSet<Detalles_Inventario> Detalles_Inventario { get; set; }
        public virtual DbSet<Detalles_Servicios> Detalles_Servicios { get; set; }
        public virtual DbSet<Errores> Errores { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<Horarios_Trabajadores> Horarios_Trabajadores { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Menu_Servicios> Menu_Servicios { get; set; }
        public virtual DbSet<municipios> municipios { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Ordenes_Trabajos> Ordenes_Trabajos { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Registro_Vehiculos> Registro_Vehiculos { get; set; }
        public virtual DbSet<Reportes> Reportes { get; set; }
        public virtual DbSet<Servicios_Domicilio> Servicios_Domicilio { get; set; }
        public virtual DbSet<Sesiones> Sesiones { get; set; }
        public virtual DbSet<sucursales> sucursales { get; set; }
        public virtual DbSet<Trabajadores> Trabajadores { get; set; }
        public virtual DbSet<Unidades_de_Medida> Unidades_de_Medida { get; set; }
        public virtual DbSet<v_citas> v_citas { get; set; }
        public virtual DbSet<v_ordenes_trabajo> v_ordenes_trabajo { get; set; }
        public virtual DbSet<v_pagos> v_pagos { get; set; }
        public virtual DbSet<v_trabajadores> v_trabajadores { get; set; }
        public virtual DbSet<v_trabajadoresactivos> v_trabajadoresactivos { get; set; }
    
        public virtual int pa_crearadministrador(string nombre, string apellidop, string apellidom, Nullable<int> id_sucursal)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidopParameter = apellidop != null ?
                new ObjectParameter("apellidop", apellidop) :
                new ObjectParameter("apellidop", typeof(string));
    
            var apellidomParameter = apellidom != null ?
                new ObjectParameter("apellidom", apellidom) :
                new ObjectParameter("apellidom", typeof(string));
    
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_crearadministrador", nombreParameter, apellidopParameter, apellidomParameter, id_sucursalParameter);
        }
    
        public virtual int pa_crearcliente(string nombre_completo, string telefono, string direccion, Nullable<System.DateTime> fecha_registro)
        {
            var nombre_completoParameter = nombre_completo != null ?
                new ObjectParameter("nombre_completo", nombre_completo) :
                new ObjectParameter("nombre_completo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("fecha_registro", fecha_registro) :
                new ObjectParameter("fecha_registro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_crearcliente", nombre_completoParameter, telefonoParameter, direccionParameter, fecha_registroParameter);
        }
    
        public virtual int pa_creartrabajador(string nombre, string apellidopaterno, string apellidomaterno, string tipo_cargo, Nullable<decimal> pago, string telefono, string id_especialidad, Nullable<int> id_sucursal)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidopaternoParameter = apellidopaterno != null ?
                new ObjectParameter("apellidopaterno", apellidopaterno) :
                new ObjectParameter("apellidopaterno", typeof(string));
    
            var apellidomaternoParameter = apellidomaterno != null ?
                new ObjectParameter("apellidomaterno", apellidomaterno) :
                new ObjectParameter("apellidomaterno", typeof(string));
    
            var tipo_cargoParameter = tipo_cargo != null ?
                new ObjectParameter("tipo_cargo", tipo_cargo) :
                new ObjectParameter("tipo_cargo", typeof(string));
    
            var pagoParameter = pago.HasValue ?
                new ObjectParameter("pago", pago) :
                new ObjectParameter("pago", typeof(decimal));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var id_especialidadParameter = id_especialidad != null ?
                new ObjectParameter("id_especialidad", id_especialidad) :
                new ObjectParameter("id_especialidad", typeof(string));
    
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_creartrabajador", nombreParameter, apellidopaternoParameter, apellidomaternoParameter, tipo_cargoParameter, pagoParameter, telefonoParameter, id_especialidadParameter, id_sucursalParameter);
        }
    
        public virtual int sp_recalcular_total_orden(Nullable<int> id_orden)
        {
            var id_ordenParameter = id_orden.HasValue ?
                new ObjectParameter("id_orden", id_orden) :
                new ObjectParameter("id_orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_recalcular_total_orden", id_ordenParameter);
        }
    }
}
