//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajadores()
        {
            this.Agendar_Citas = new HashSet<Agendar_Citas>();
            this.Cotizaciones = new HashSet<Cotizaciones>();
            this.Horarios_Trabajadores = new HashSet<Horarios_Trabajadores>();
            this.Ordenes_Trabajos = new HashSet<Ordenes_Trabajos>();
            this.Reportes = new HashSet<Reportes>();
            this.Servicios_Domicilio = new HashSet<Servicios_Domicilio>();
        }
    
        public int id_trabajador { get; set; }
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellidopaterno { get; set; }
        public string apellidomaterno { get; set; }
        public string id_tipo_cargo { get; set; }
        public decimal pago { get; set; }
        public string telefono { get; set; }
        public string id_especialidad { get; set; }
        public byte[] activo { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public long ledger_start_transaction_id { get; set; }
        public Nullable<long> ledger_end_transaction_id { get; set; }
        public long ledger_start_sequence_number { get; set; }
        public Nullable<long> ledger_end_sequence_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendar_Citas> Agendar_Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios_Trabajadores> Horarios_Trabajadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Trabajos> Ordenes_Trabajos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reportes> Reportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios_Domicilio> Servicios_Domicilio { get; set; }
        public virtual Sesiones Sesiones { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
