//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_citas
    {
        public int id_cita { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public System.TimeSpan hora_cita { get; set; }
        public string motivo_cancelacion { get; set; }
        public string nombre_cliente { get; set; }
        public string telefono_cliente { get; set; }
        public string marca { get; set; }
        public string tipo_combustible { get; set; }
        public int kilometraje { get; set; }
        public string nombre_trabajador { get; set; }
        public string id_tipo_cargo { get; set; }
        public string telefono_trabajador { get; set; }
        public Nullable<int> id_cotizacion { get; set; }
        public Nullable<decimal> total_estimado { get; set; }
        public string estatus_cotizacion { get; set; }
    }
}
