//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ordenes_trabajo
    {
        public int id_orden { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string estado_trabajo { get; set; }
        public string diagnostico { get; set; }
        public string observaciones { get; set; }
        public decimal total { get; set; }
        public Nullable<int> kilometraje_ingreso { get; set; }
        public Nullable<int> kilometraje_salida { get; set; }
        public string nombre_cliente { get; set; }
        public string telefono_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public string color { get; set; }
        public string tipo_combustible { get; set; }
        public string nombre_empleado { get; set; }
        public string id_tipo_cargo { get; set; }
        public Nullable<int> id_cotizacion { get; set; }
        public Nullable<decimal> total_estimado { get; set; }
        public string estatus_cotizacion { get; set; }
        public decimal total_servicios { get; set; }
        public decimal total_refacciones { get; set; }
        public decimal saldo_pendiente { get; set; }
    }
}
