//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pagos
    {
        public int id_pago { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string metodo_pago { get; set; }
        public string tipo_pago { get; set; }
        public decimal monto { get; set; }
        public decimal saldo_pendiente { get; set; }
        public string estatus { get; set; }
    }
}
