//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_trabajadores
    {
        public int id_trabajador { get; set; }
        public string nombre_completo { get; set; }
        public string id_tipo_cargo { get; set; }
        public string id_especialidad { get; set; }
        public string telefono { get; set; }
        public byte[] activo { get; set; }
    }
}
